#!/bin/sh
set -e -x

chmod +x /opt/microsoft/powershell/6/pwsh

adduser -D powershell

mkdir -p /data || true

chown powershell:powershell /data

pwsh -Command Install-Module Az -RequiredVersion 1.4.0 -Force

# CIS Benchmarking
touch /etc/login.defs
chmod 0444 /etc/login.defs

chmod 0600 /etc/shadow

#Install DotNetCoreSDK
wget -O dotnet.tar.gz https://dotnetcli.blob.core.windows.net/dotnet/Sdk/$DOTNET_SDK_VERSION/dotnet-sdk-$DOTNET_SDK_VERSION-linux-musl-x64.tar.gz \
    && dotnet_sha512='18c821c8f9c110d3e1bc4e8d6a88e01c56903a58665a23a898457a85afa27abfa23ef24709602d7ad15845f1cd5b3c3dd8c24648ab8ab9e281b5705968e60e41' \
    && echo "$dotnet_sha512  dotnet.tar.gz" | sha512sum -c - \
    && mkdir -p /usr/share/dotnet \
    && tar -C /usr/share/dotnet -xzf dotnet.tar.gz \
    && ln -s /usr/share/dotnet/dotnet /usr/bin/dotnet \
    && rm dotnet.tar.gz

# Trigger first run experience by running arbitrary cmd to populate local package cache
dotnet help