#!/bin/sh
set -e -x

#Install DotNetCoreSDK
wget -O dotnet.tar.gz https://dotnetcli.blob.core.windows.net/dotnet/Sdk/$DOTNET_SDK_VERSION/dotnet-sdk-$DOTNET_SDK_VERSION-linux-musl-x64.tar.gz
echo "$DOTNET_SHA512  dotnet.tar.gz" | sha512sum -c -
mkdir -p /usr/share/dotnet
tar -C /usr/share/dotnet -xzf dotnet.tar.gz
ln -s /usr/share/dotnet/dotnet /usr/bin/dotnet
rm dotnet.tar.gz

# Trigger first run experience by running arbitrary cmd to populate local package cache (NUGET)
dotnet help &> /dev/null

chmod +x /opt/microsoft/powershell/6/pwsh

adduser -D powershell

mkdir -p /data || true

chown powershell:powershell /data

pwsh -Command Install-Module Az -RequiredVersion 1.4.0 -Force

# CIS Benchmarking
touch /etc/login.defs
chmod 0444 /etc/login.defs

chmod 0600 /etc/shadow

